import './css/reset.css';
import './css/normalize.css';
import './css/globals.css';
import { Noto_Sans_KR } from 'next/font/google';
import { Jua } from 'next/font/google';

const sans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const dongle = Jua({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={sans.className}>{children}</body>
    </html>
  );
}
